Cray-HPE/cray-etcd

charts/cray-etcd-backup/Chart.yaml, charts/cray-etcd-backup/files/list_backups, charts/cray-etcd-operator/Chart.yaml, charts/cray-etcd-operator/templates/wait-jobs.yaml, charts/cray-etcd-operator/values.yaml
* Bring in 0.12.4-cray docker image (curl image fix)
* Fix wait for job
* Fix list script when no backups available yet
(necessary to get etcd cluster restores working again in 1.2)
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [CASMINST-3640](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3640)
vshasta -- tested period backups and restores of cray-bss and cray-bos etcd clusters
* `vshasta`
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
Low -- already broken
=> A few fixes cray-etcd-backup and cray-etcd-operator to get restores working

charts/cray-etcd-operator/Chart.yaml, charts/cray-etcd-operator/values.yaml
Pull in new etcd operator image pinning to specific version of curl.
* Resolves [CASMTRIAGE-3194](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3194)
```
Normal   Pulling           16s                kubelet            Pulling image "curlimages/curl:7.73.0"
Normal   Pulled            15s                kubelet            Successfully pulled image "curlimages/curl:7.73.0" in 903.549441ms
```
* `vshasta`
Used the updated operator image with pinned version, was able to pull the image during restore.
Low
=> Pin curl image to specific version

charts/cray-etcd-backup/Chart.yaml, charts/cray-etcd-backup/files/create_backup, charts/cray-etcd-backup/templates/configmap.yaml
Also remove externaldns backup -- no longer there, and fix benign but confusing shell error when creating manual backup.
* Resolves [CASMPET-5638](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5638)
```
ncn-m001-fec36008:/opt/cray/platform-utils/s3 # ./list-objects.py --bucket-name etcd-backup | grep uas
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:14:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:15:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:16:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:17:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:18:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:19:09
cray-uas-mgr/etcd.backup_v10_2022-05-17-16:20:09
```
```
ncn-m001-fec36008:/home/bklein # kubectl exec -it -n operators $(kubectl get pod -n operators | grep etcd-backup-restore | head -1 | …
```
=> Add cray-uas-mgr to etcd backup list

charts/cray-etcd-backup/Chart.yaml, charts/cray-etcd-backup/files/create_backup, charts/cray-etcd-backup/files/create_periodic_backups.sh, charts/cray-etcd-backup/templates/clusterrole.yaml, charts/cray-etcd-backup/templates/post-upgrade.yaml
In LANL tycho enviromment, the bos etcd backups had been timing out for many days.
This environment has 14 workers, 2688 compute nodes in 11 Olympus cabinets.
The default timeout is 1 min, once the timeout was increased, the backups started to succeed.
The timeout was increased to 10 min for all etcdbackups and a post-upgrade hook was added to allow for the etcdbackup resources to get re-created with the added backupPolicy.timeoutInSecond value.
This is targeted for CSM 1.3.
A troubleshooting doc change will be made for CSM 1.2.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [CASMTRIAGE-4188](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4188)
* Change will also be needed in `<insert branch name here>` …
=> CASMTRIAGE-4188 master : LANL DDR5 tycho bos etcd backup has not run for 9 days

charts/cray-etcd-operator/Chart.yaml
Modified local sub-chart was ignored due to helm dependency -- change to use the local copy which includes clusterrole changes to support auto-heal.
* Resolves [CASMPET-6121](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6121)
```
time="2022-11-22T20:53:53Z" level=info msg="Checking for existing restore that needs to be cleaned up." cluster-name=cray-bos-etcd cluster-namespace=services pkg=cluster
time="2022-11-22T20:53:53Z" level=info msg="execing into pod etcd-backup-restore-7848575c4f-4cmlc to restore" cluster-name=cray-bos-etcd cluster-namespace=services pkg=cluster
time="2022-11-22T20:53:54Z" level=info msg="attempting restore from backup : etcd.backup_v7388_2022-11-22-18:15:10" cluster-name=cray-bos-etcd cluster-namespace=services pkg=cluster
time="2022-11-22T20:53:54Z" …
```
=> Use local version of etcd operator helm chart

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/templates/migration-jobs.yaml, charts/cray-etcd-base/values.yaml, charts/cray-etcd-migration-setup/Chart.yaml, charts/cray-etcd-migration-setup/templates/rbac.yaml
The bitnami chart doesn't yet support different labels for the snapshotter and etcd pods.  Until we fix that we'll remove the common labels from the cronjob spec.
* Resolves [CASMTRIAGE-4964](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4964)
```
pod/cray-bos-bitnami-etcd-0                                           2/2     Running            0          3m18s   10.34.0.46   ncn-w003-27ff67ca   <none>           <none>
pod/cray-bos-bitnami-etcd-1                                           2/2     Running            0          4m28s   10.44.0.46   ncn-w001-b76eaea2   <none>           <none>
pod/cray-bos-bitnami-etcd-2                                           2/2     Running            0          5m51s   10.43.0.21   ncn-w002-961b961b   <none>           <none> …
```
=> Remove labels allowing snapshotter pod to schedule on TDS systems

charts/cray-etcd-defrag/Chart.yaml, charts/cray-etcd-defrag/files/etcd_defrag.sh, charts/cray-etcd-defrag/templates/clusterrole.yaml, charts/cray-etcd-defrag/templates/cronjob-single-etcd.yaml, charts/cray-etcd-defrag/templates/cronjob.yaml, charts/cray-etcd-defrag/values.yaml
Update defrag jobs for new bitnami etcd statefulsets
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6375
* ashton
```
pit:~/brad # kubectl logs -n services pod/kube-etcd-defrag-27973386-d5c5p
Running etcd defrag for: all
Skip defrag for: cray-hbtd-etcd
Skipping defrag for: cray-hbtd-etcd
Defragging cray-bos-bitnami-etcd-0
Defragging cray-bos-bitnami-etcd-1
Defragging cray-bos-bitnami-etcd-2
Completed
```
```
{"level":"info","ts":"2023-03-09T23:06:08.418Z","caller":"backend/backend.go:497","msg":"defragmenting","path":"/bitnami/etcd/data/member/snap/db","current-db-size-bytes":225280,"current-db-size":"225 kB","current-db-size-in-use-bytes":225280,"current-db-size-in-use":"225 kB"}
{"level":"info","ts":"2023-03-09T23:06:08.446Z","caller":"backend/backend.go:549","msg":"finished …
```
=> Refactor defrag process for bitnami etcd chart

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/templates/migration-jobs.yaml
Migrate data from old etcd operator cluster whenever possible.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6428
* vshasta
```
ncn-m001-e2e75ea1:/home/bklein # kubectl logs -n services cray-bos-pre-upgrade-etcd-backup-wbjfl -f
Creating /snapshots/cray-bos-bitnami-etcd directory for snapshots...
Changing ownership of /snapshots/cray-bos-bitnami-etcd to etcd user
cray-bos-etcd-client found, proceeding with migrating current data...
Taking snapshot from cray-bos-etcd-45ctzq6vwx...
2023-03-20 16:44:35.287502 I | clientv3: opened snapshot stream; downloading
2023-03-20 16:44:35.288638 I | clientv3: completed snapshot read; closing
Snapshot saved at snapshot.db
Copying snapshot from cray-bos-etcd-45ctzq6vwx to /tmp/cray-bos_etcd_migration.snapshot.db...
Grabbing keys and S3 endpoint …
```
=> Migrate data from old operator irrespective of backup config

charts/cray-etcd-backup/Chart.yaml, charts/cray-etcd-backup/files/create_backup, charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/templates/migration-jobs.yaml, charts/cray-etcd-base/values.yaml
Later code for bitnami etcd chart and fixes for CLBO after power off/on.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6365
* `ashton`
Scale down to zero and back up to three members:
```
etcd 19:09:19.70
etcd 19:09:19.70 Welcome to the Bitnami etcd container
etcd 19:09:19.71 Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 19:09:19.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 19:09:19.73
etcd 19:09:19.74 INFO  ==> ** Starting etcd setup **
etcd 19:09:19.77 INFO  ==> Validating settings in ETCD_* env vars..
etcd 19:09:19.80 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 19:09:19.82 INFO  ==> …
```
=> Update bitnami docker image with latest (CASMPET-6365)

charts/cray-etcd-migration-setup/Chart.yaml, charts/cray-etcd-migration-setup/values.yaml
Increase size of etcd cephfs pvc for snapshots.  Going with 200G which should leave more than enough space based on audit of current usage of the etcd-backups bucket:
```
11958904 ~12G (mug)
14889340 ~14G (baldar)
17817388 ~17G (shandy)
21434928 ~21G (hela)
```
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6419
* `ashton`
```
ncn-m002:~ # kubectl get pvc -n services bitnami-etcd-snapshotter -o json | jq -r .spec.resources.requests.storage
200G
```
Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing
=> Increase size of common etcd snapshot PVC (CASMPET-6419)

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/tests/etcd-enabled_test.yaml, charts/cray-etcd-base/values.yaml
Bring in latest bitnami etcd images with upstream merges
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6504
```
ncn-m002:~ # /opt/cray/platform-utils/etcd/etcd-util.sh create_backup cray-bos brad-manual-1
Taking snapshot from cray-bos-bitnami-etcd-1...
Pushing newly created snapshot /snapshots/cray-bos-bitnami-etcd/db-2023-04-24_18-15 to S3 as brad-manual-1 for cray-bos
upload: snapshots/cray-bos-bitnami-etcd/db-2023-04-24_18-15 to s3://etcd-backup/cray-bos/brad-manual-1
```
```
ncn-m002:~ # /opt/cray/platform-utils/etcd/etcd_restore_rebuild.sh -s cray-bos
The following etcd clusters will be restored/rebuilt:
cray-bos
You will be accepting responsibility for any missing data if there is a
restore/rebuild over a running etcd k/v. HPE assumes no responsibility.
Proceed …
```
=> Consume upstream changes which have merged for bitnami etcd (CASMPET-6504)

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/values.yaml
New bitnami images with power off/on fix and set ETCD_DISABLE_PRESTOP option.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6642
Tested on ashton:
After simulating power off/on, cray-bos (with this fix) was the only one to start cleanly:
```
services         cray-bos-bitnami-etcd-0                                           2/2     Running                 2 (19m ago)       38m
services         cray-bos-bitnami-etcd-1                                           2/2     Running                 3 (3m45s ago)     38m
services         cray-bos-bitnami-etcd-2                                           2/2     Running                 2 (19m ago)       38m
services         cray-bos-bitnami-etcd-snapshotter-28122840-ld7fr                  0/2     Completed               0                 78m …
```
=> Fix system power off/on CLBO issue with bitnami etcd pods (CASMPET-6642)

Jenkinsfile.github, Makefile, charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/templates/configmap.yaml, charts/cray-etcd-test/.gitignore, charts/cray-etcd-test/Chart.yaml, charts/cray-etcd-test/files/etcd-load.sh, charts/cray-etcd-test/templates/configmap.yaml, charts/cray-etcd-test/values.yaml
This change populates the etcd config file with settings specified in extraEnvVars, as etcd does not honor a mix of config file and env var settings.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6572
Mug:
```
ncn-m001:~/brad # kubectl exec -it -n services cray-etcd-test-bitnami-etcd-2 -c etcd -- /bin/bashI have no name!@cray-etcd-test-bitnami-etcd-2:/opt/bitnami/etcd$ cat conf/etcd.yaml
name: cray-etcd-test-bitnami-etcd-2
initial-cluster: "cray-etcd-test-bitnami-etcd-0=http://cray-etcd-test-bitnami-etcd-0.cray-etcd-test-bitnami-etcd-headless.services.svc.cluster.local:2380,cray-etcd-test-bitnami-etcd-1=http://cray-etcd-test-bitnami-etcd-1.cray-etcd-test-bitnami-etcd-headless.services.svc.cluster.local:2380,cray-etcd-test-bitnami-etcd-2=http://cray-etcd-test-bitnami-etcd-2.cray-etcd-t …
```
=> Populate etcd config file with env vars (CASMINST-6572)

charts/cray-etcd-backup/Chart.yaml, charts/cray-etcd-backup/values.yaml, charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/values.yaml, charts/cray-etcd-defrag/Chart.yaml, charts/cray-etcd-defrag/templates/cronjob.yaml, charts/cray-etcd-defrag/values.yaml, charts/cray-etcd-test/Chart.yaml, charts/cray-etcd-test/values.yaml
Update cray-etcd-base with upstream changes (no more patching upstream image)
* CASMPET-6758: update bitnami-etcd container with upstream merge
beau:
```
pod/cray-etcd-test-bitnami-etcd-0                                     2/2     Running     0               58m
pod/cray-etcd-test-bitnami-etcd-1                                     2/2     Running     0               60m
pod/cray-etcd-test-bitnami-etcd-2                                     2/2     Running     0               61m
```
```
ncn-m001:~ # /opt/cray/platform-utils/etcd/etcd-util.sh endpoint_status cray-etcd-test
+----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | …
```
=> Update bitnami container images and chart for CSM 1.6 (CASMPET-6758)

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/templates/migration-jobs.yaml, charts/cray-etcd-test/Chart.yaml
Fix upgrade issue with bitnami etcd chart (introduction of new label).
* CASMPET-6831: bitnami CSM 1.6 base chart upgrade fails due to immutable statefulset field(s)
beau 
```
pit:~/brad # loftsman ship --manifest-path ./manifest-new.yaml --charts-path ./helm
2023-11-01T21:06:27Z INF Initializing the connection to the Kubernetes cluster using KUBECONFIG (system default), and context (current-context) command=ship
2023-11-01T21:06:27Z INF Initializing helm client object command=ship
|\
| \
|  \
|___\      Shipping your Helm workloads with Loftsman
\--||___/
~~~~~~\_____/~~~~~~~
2023-11-01T21:06:27Z INF Ensuring that the loftsman namespace exists command=ship
2023-11-01T21:06:27Z INF Loftsman will use the packaged charts at ./helm as the Helm install source command=ship
2023-11-01T21:06:27Z …
```
=> Fix upgrade label issue with latest bitnami chart (CASMPET-6831)

charts/cray-etcd-test/Chart.yaml
Fix upgrade issue with bitnami etcd chart (introduction of new label).
* CASMPET-6831: bitnami CSM 1.6 base chart upgrade fails due to immutable statefulset field(s)
beau 
```
pit:~/brad # loftsman ship --manifest-path ./manifest-new.yaml --charts-path ./helm
2023-11-01T21:06:27Z INF Initializing the connection to the Kubernetes cluster using KUBECONFIG (system default), and context (current-context) command=ship
2023-11-01T21:06:27Z INF Initializing helm client object command=ship
|\
| \
|  \
|___\      Shipping your Helm workloads with Loftsman
\--||___/
~~~~~~\_____/~~~~~~~
2023-11-01T21:06:27Z INF Ensuring that the loftsman namespace exists command=ship
2023-11-01T21:06:27Z INF Loftsman will use the packaged charts at ./helm as the Helm install source command=ship
2023-11-01T21:06:27Z …
```
=> Update cray-etcd-test chart now that cray-etcd-base 1.1.1 has published (CASMPET-6831)

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/values.yaml
When bitnami-etcd has a configuration file, it ignores all other environment variables that are normally used for etcd configuration. To fix this, this PR puts environment variables into the configuration file. Previously, we had noticed etcd filling up because auto-compaction-retention and auto-compaction-mode were not being set. These variables will now be put in the configuration file and etcd is performing much better.
* Resolves [CASMPET-6876](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6876)
_List the environments in which these changes were tested._
* lemondrop by @mjendrysik-hpe 
* Beau by @leliasen-hpe 
On lemondrop, cray-power-control-bitnami-etcd was deployed with this change that puts the environment variables in the configuration file. It was observed that etcd was in a …
=> CASMPET-6876 add environment variables to etcd config file

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/values.yaml
When bitnami-etcd has a configuration file, it ignores all other environment variables that are normally used for etcd configuration. To fix this, this PR puts environment variables into the configuration file. Previously, we had noticed etcd filling up because auto-compaction-retention and auto-compaction-mode were not being set. These variables will now be put in the configuration file and etcd is performing much better.
* Resolves [CASMPET-6876](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6876)
_List the environments in which these changes were tested._
* lemondrop by @mjendrysik-hpe 
* Beau by @leliasen-hpe 
On lemondrop, cray-power-control-bitnami-etcd was deployed with this change that puts the environment variables in the configuration file. It was observed that etcd was in a …
=> Casmpet 6876 release 1.5

charts/cray-etcd-base/Chart.yaml, charts/cray-etcd-base/templates/certificates.yaml, charts/cray-etcd-test/Chart.yaml, charts/cray-etcd-test/values.yaml
In CSM 1.6, cert-manger is being upgraded to v1.12.9. This means the cert-manager.io/v1alpha2 api is being removed. Cray-etcd-base chart needs to be updated to use cert-manager.io/v1.
I tested deploying the cray-etcd-test chart on Beau.
My initial test, showed that the chart failed to deploy when the API was not updated. This is expected since that API has disappeared.
```
ncn-m001:~ # helm upgrade -n services cray-etcd-test cray-etcd-test-1.0.2-20240516143337+7a5adb9.tgz
Error: UPGRADE FAILED: [resource mapping not found for name: "cray-etcd-test-etcd-server-tls" namespace: "" from "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
```
My second test showed that I had changed the API in the certificate.yaml file incorrectly. The chart failed to deploy when I had …
=> CASMPET-6904 update the cert-manager API in etcd-base chart

charts/cray-etcd-backup/Chart.yaml, charts/cray-etcd-backup/templates/cronjob.yaml
CronJob apiVersion `batch/v1` has been around since k8s 1.21.  CronJob apiVersion `batch/v1beta1` is deprecated in K8s 1.25+.  Use `batch/v1` in prep for K8s upgrade to 1.32.
* Resolves [CASMPET-7374](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7374)
Was able to successfully install on `molly`:
```
pit:~/studenym/cray-etcd-backup # helm install -n services cray-etcd-backup .
NAME: cray-etcd-backup
LAST DEPLOYED: Thu Feb  6 17:26:25 2025
NAMESPACE: services
STATUS: deployed
REVISION: 1
TEST SUITE: None
pit:~/studenym/cray-etcd-backup # kubectl get pods -n services | grep etcd
etcd-backup-restore-65966cd9f6-mk2mv                     1/1     Running                      0                 17s
etcd-backup-restore-65966cd9f6-xlj2t                     1/1     Running                      0 …
```
=> CASMPET-7374: Use apiVersion 'batch/v1' in cray-etcd-backup cronjob.yaml template
